ds_list_add(global.TxtLst,"Después del 2015 todo comenzó a echarse a perder.");
ds_list_add(global.TxtLst,"El metro estaba muy silencioso. Hubiera preferido que estuviera lleno, como antes.");
ds_list_add(global.TxtLst,"No me puedo sacar esos gritos de la cabeza.");
ds_list_add(global.TxtLst,"El sonido de carne desgarrándose, luego, masticar, masticar y tragar.");
ds_list_add(global.TxtLst,"No encuentro a mi perro.Llevó quién sabe cuánto tratando de encontrarlo para darle este brazo.");
ds_list_add(global.TxtLst,"Tengo tanta hambre...");
ds_list_add(global.TxtLst,"¡Ah, qué fresco se siente! Ya no me pica la piel.");
ds_list_add(global.TxtLst,"Ven, por favor. Por favor, no te vayas. Tengo tanta hambre...");
ds_list_add(global.TxtLst,"Rojo...yo tenía un suéter rojo...¿o era un vestido?");
ds_list_add(global.TxtLst,"Perdóname, papá. Es que tenía mucha hambre.");
ds_list_add(global.TxtLst,"Antes había más gente en el metro. Ahora no hay nadie. Tengo tanta hambre...");
ds_list_add(global.TxtLst,"La caja estaba llena...sólo quedan tres balas...solo tres balas...");
ds_list_add(global.TxtLst,"¿Por qué gritan? ¿Por qué gritan tanto? Es bonito cuando dejan de gritar.");
ds_list_add(global.TxtLst,"Tantas cosas en tu camino y nada qué comer...");
ds_list_add(global.TxtLst,"Tantos puntos, marca tantos puntos...");
ds_list_add(global.TxtLst,"No escuchas nada. De repente, algo se rompe, algo choca con otra cosa. Y ésas 'cosas' se acercan cada vez más.");
ds_list_add(global.TxtLst,"De noche es peor. De día, los ves.");
ds_list_add(global.TxtLst,"A veces ves las pisadas en la tierra.");
ds_list_add(global.TxtLst,"Recuerdo cuando había más sonidos. Ahora sólo hay silencio. Silencio y gritos. Luego, masticar, masticar.");
ds_list_add(global.TxtLst,"Son tantos, cada vez más.");
ds_list_add(global.TxtLst,"Ahora corro para escapar.");
ds_list_add(global.TxtLst,"Ahora corro para comer.");
ds_list_add(global.TxtLst,"Los perros ladran, las aves trinan, pero sólo los gritos los hacen correr.");
ds_list_add(global.TxtLst,"El calor, el frío, el viento, no importan.");
ds_list_add(global.TxtLst,"Recuerdo esa foto. No, no es una foto, es una pintura. No, no es una cara.");
ds_list_add(global.TxtLst,"El sol no me quema la piel. No tengo piel.");
ds_list_add(global.TxtLst,"El olor a carne descompuesta es constante.");
ds_list_add(global.TxtLst,"Fué en mayo, ella no sobrevivió.");
ds_list_add(global.TxtLst,"Maldito García, los dejó morir y ahora estamos indefensos.");
ds_list_add(global.TxtLst,"El 26 de abril logré encontrar un refugio con suficientes provisiones para un mes.");
ds_list_add(global.TxtLst,"el ambiente era enrarecido, el olor metálico de la sangre era tan penetrante que aturdía");
ds_list_add(global.TxtLst,"¡Shhhh!... silencio...");
ds_list_add(global.TxtLst,"Las luces morían poco a poco con el paso de los días, el suministro eléctrico languidecía.");
ds_list_add(global.TxtLst,"¡A prisa, corre, corre!");
ds_list_add(global.TxtLst,"Suponía que el agua era pura, nunca conté con que la inmundicia la contaminaría, eso fué lo que la mató, pobre alma...");
ds_list_add(global.TxtLst,"Los niños o... lo que ahora sean... ¡caben por todas partes!");
ds_list_add(global.TxtLst,"Después de salir de Tlalpan encontramos un bloqueo de autos, durante el embotellamiento salieron de ellos y huyeron, muy pocos tuvieron suerte.");
ds_list_add(global.TxtLst,"Iztacalco fue una de las primeras en caer, la densa población permitió la propagación de... eso.");
ds_list_add(global.TxtLst,"Al poco tiempo el Centro Histórico se convertiría en una tumba, a muchos los agarró desprevenidos.");
ds_list_add(global.TxtLst,"Sin importar lo que suceda no salgas durante la noche, eres más vulnerable, no sé porqué.");
ds_list_add(global.TxtLst,"Muchos murieron por el descarrilamiento del metro, infelices afortunados.");
ds_list_add(global.TxtLst,"El día que inició todo era mi cumpleaños, la vida me dió mi regalo con un escalofriante e irónico sentido del humor.");
ds_list_add(global.TxtLst,"¡Puta madre, van a morir quemados si no los ayudamos!");
ds_list_add(global.TxtLst,"Mientras dormitaba sentí su respiración en mi cara, era cachorro aún, tenía hambre pero no tanto como para atreverse a atacarme, le dí un poco de comida, a cambio me alertaría cuando vinieran.");
ds_list_add(global.TxtLst,"Encontré a Laurita arrinconada en el closet, le tomó algo de tiempo confiar en mí, no duró mucho a mi lado, espero haya llegado al refugio.");
ds_list_add(global.TxtLst,"En una semana todo estaba devastado, el ejército intentó en vano ayudar a la población, ‘eso’ se propagaba más rápido que el viento.");
ds_list_add(global.TxtLst,"Nunca pense ver buitres en Santa Fé, y no me refiero a esos empresarios rapiñeros.");
ds_list_add(global.TxtLst,"Caminábamos intentando llegar a nuestros hogares, no sabíamos lo que ocurría.");
ds_list_add(global.TxtLst,"Algunos caminaban en grupos pequeños, se reducían poco a poco, conforme llegaban a casa.");
ds_list_add(global.TxtLst,"¡Dios, esa peste de nuevo!");
ds_list_add(global.TxtLst,"Mi niñez fue feliz, nunca imaginé terminar así. ");
ds_list_add(global.TxtLst,"¡No es posible perdí el arma!");
ds_list_add(global.TxtLst,"Tengo que salir de la ciudad, solo espero que en el campo no haya estas cosas.");
ds_list_add(global.TxtLst,"Por fin logramos salir de la ciudad, en la carretera se veían autos abandonados y cristales rotos.");
ds_list_add(global.TxtLst,"No podíamos circular rápido por la carretera, nos movíamos en pequeñas caravanas.");
ds_list_add(global.TxtLst,"Siempre pensé que los Zombies eran los Godínez, pero esto no es gracioso.");
ds_list_add(global.TxtLst,"Lo bueno es que mi suegra seguramente les cayó mal y la vomitaron.");
ds_list_add(global.TxtLst,"Son risibles sus estúpidos rostros, hasta que los tienes a menos de un metro.");
ds_list_add(global.TxtLst,"El silencio es aterrador.");
ds_list_add(global.TxtLst,"No sé cuánto tiempo pueda sobrevivir, quedan pocas provisiones y el agua escasea.");
ds_list_add(global.TxtLst,"No siento mi mano, ni mi pierna, espero no habermelas roto con la caída, sería el fin.");
ds_list_add(global.TxtLst,"Le hice un favor al infeliz y le pegué un tiro, fue un trago muy amargo.");
ds_list_add(global.TxtLst,"Cuando vi morir a esos niños fue el colmo de mi cordura, no podía más…");
ds_list_add(global.TxtLst,"Es un mundo surreal, las comunicaciones cada vez son más aisladas y la luz más escasa.");
ds_list_add(global.TxtLst,"Nadie sabía lo que estaba pasando, solo veías patrullas y sirenas ir y venir.");
ds_list_add(global.TxtLst,"No se dirijan a Mixcoac, parece que ahí empezó todo.");
ds_list_add(global.TxtLst,"El avión se desplomó al poco de haber despegado, arrasó con muchas casas.");
ds_list_add(global.TxtLst,"¡No toques mis cosas o te corto la mano y te parto la cara!");
ds_list_add(global.TxtLst,"La histeria iba en aumento, todos querían salir del andén, muchos murieron pisados o aplastados.");
ds_list_add(global.TxtLst,"Nunca pude comunicarme con mi familia, cuando llegué se habían ido.");
ds_list_add(global.TxtLst,"Mh… recuerdo esa canción, ahora suena a broma de mal gusto.");
ds_list_add(global.TxtLst,"El olor a rosas fue un recordatorio de que no todo puede ser malo.");
ds_list_add(global.TxtLst,"¡Cómo nos gustaba comer! no habíamos terminado de cenar y ya hablábamos de comida.");
ds_list_add(global.TxtLst,"Dicen que ya hay problemas en E.E.U.U. ni Rambo creo que los salve, fue tan repentino…");
ds_list_add(global.TxtLst,"De que lloren en mi casa a que lloren en la suya, pues que chingue a su madre…");
ds_list_add(global.TxtLst,"El frío es mucho, pero más el frío del silencio.");
ds_list_add(global.TxtLst,"Vaya, la vía láctea no era un mito.");
ds_list_add(global.TxtLst,"La explosión incineró  todo a dos cuadras a la redonda.");
ds_list_add(global.TxtLst,"Las ardillas se podrán dar un festín con tanto cacahuate en las tiendas.");
ds_list_add(global.TxtLst,"Están desmembrados y aún así se mueven.");
ds_list_add(global.TxtLst,"Sus ojos muertos llenos de terror me sobrecojen cada noche, ¿por qué no los ayudé?");

